from enum import Enum


class AllowedSurface(str, Enum):
    FOUND = "FOUND"
    NOT_FOUND = "NOT_FOUND"
    VERSION_DRIFT = "VERSION_DRIFT"
    TOMBSTONED = "TOMBSTONED"
    MANIFEST_MISMATCH = "MANIFEST_MISMATCH"
    REPLAY_FAIL = "REPLAY_FAIL"
    CRAWLER_BLOCKED = "CRAWLER_BLOCKED"
