name: resolver-ci

on:
  workflow_dispatch:
  push:
    branches: [ master, main, develop ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build
        run: forge build --sizes --extra-output-files bin

      - name: Test
        run: forge test -vvv --gas-report

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resolver-build
          path: out/
